### ISSUE TITLE
Midterm feedback

### ISSUE THREAD

**Issue by miguelgfierro** [RecandChat/CodeCompass#36]
- [x] If the project is called Compas, you should rename the repo
- [x] If your project is compas, then the library typically has the same name of the project https://github.com/RecandChat/Github-Recommendation-System/tree/main/monkelib if it is monkey, then monkey. This is a recommendation because you can name the library whatever you want. You decide. 
- [x] Typically the test folder is in the root https://github.com/RecandChat/Github-Recommendation-System/tree/main/monkelib/Tests
- [x] Don't add CSV files to the repo https://github.com/RecandChat/Github-Recommendation-System/tree/main/monkelib/Data/original use a different storage
- [x] https://github.com/RecandChat/Github-Recommendation-System/blob/7575c35d8bad9c1a350afa026086baa614a791bc/monkelib/Tests/test_functional.py#L2C1-L3C1 it is not a good practice to do import *, better to name each
- [x] Create a MLOps pipeline like in https://github.com/miguelgfierro/project_template/actions everytime someone does a PR to main, the test execute
- [x] Create a release for every delivery point https://github.com/miguelgfierro/project_template/releases/tag/0.1.1
- [x] Parse the code in the repo, use LLM embeddings to make better recommendation
- [x] Explain the details and math behind each of the algos you use: word2vec, KNN
- [x] The repo I was talking about is https://github.com/miguelgfierro/hoap3_read_sensors 
- [x] Nice final outcome: given a user recommend them the repos that they would like, like the recommendations you can see in github.com
- [x] All imports should go in the top cell instead of in between, otherwise you have the risk of an import error in the middle of your computation.
- [x] Remove configuration files like https://github.com/RecandChat/CodeCompass/tree/v1.0.0/monkelib/models/__pycache__ and ignore them with .gitignore
- [x] Consider doing a short demo of the final solution as a gif or YouTube that you can place in the main README

**Comment by felixggj** [comment]
All done @miguelgfierro !
